### ISSUE TITLE
Could not add as a reference to Xamarin.mac Project

### ISSUE THREAD

**Issue by mehmet6parmak** [khellang/MimeTypes#14]
Hello,

I've tried using this library in a Xamarin.mac project but got the following error. 
Is it normal? 

> Could not install package 'MimeTypes 2.4.0'. You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by khellang** [comment]
The package has targets for .NET Standard 2.0 and 2.1, which should support Xamarin.Mac 3.8 and 5.16 [according to this](https://docs.microsoft.com/nb-no/dotnet/standard/net-standard?tabs=net-standard-2-0). I'm not going to add additional targets in order to support older versions of Xamarin.Mac, unfortunately.
