### ISSUE TITLE
Incorrect MP4 Mime Type

### ISSUE THREAD

**Issue by Miriyo1975** [khellang/MimeTypes#21]
Hi,

In version 2.4.0 MP4 MIME type was correctly returning **video/mp4** but in 2.4.1 it returns **application/mp4**.

If an MP4 file contains video the MIME type should be **video/mp4**. If it is a file with just e.g. subtitles or metadata, then **application/mp4** would be correct. Is the video/mp4 option not the more common file?

![image](https://github.com/khellang/MimeTypes/assets/129769093/db27c0d7-83df-4671-81f1-056a5af255b0)
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter

**Comment by khellang** [comment]
See https://github.com/khellang/MimeTypes/issues/18#issuecomment-1569528768.

**Comment by aradalvand** [comment]
It's worth noting that Chrome plays the video inline when the `Content-Type` is `video/mp4` — which is the expected behavior when it comes to MP4 videos — on the other hand, it doesn't even seem to recognize `application/mp4`; so it very much seems like `video/mp4` is preferable here.

@khellang Could you please consider reverting this change?
