### ISSUE TITLE
Exception when file name is null

### ISSUE THREAD

**Issue by ekisielinski** [khellang/MimeTypes#9]
If method signature allows null string, why it throws exception?

https://github.com/khellang/MimeTypes/blob/d1e9e373eac1ed3fca43d37e7da1b1ea1f9bab7e/src/MimeTypes/MimeTypes.cs.pp#L1057

**Comment by khellang** [comment]
Umm. Good catch! @gfoidl I assume this shouldn't be nullable? 🤔

**Comment by ekisielinski** [comment]
It depends on your design. Usually methods like TrySomething allows nulls. GetMimeType should throw ArgumentNullException for null string (because string supports Null Object Pattern - string.Empty). So I think you should remove ? from method signature.

**Comment by gfoidl** [comment]
Yeah, @ekisielinski is correct. We should remove the `?` when null is validated and an ArgumentNullException thrown, so that the compilers knows that null isn't "tolerated". 
For the Try-method null is allowed, so here the `?` is correct.

Sorry, that's my fault. My brain was at a preview-stage of nullability and didn't update to the release along the way with updated [guidlines](https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/api-guidelines/nullability.md#annotation-guidance) on how to annotate...

**Comment by khellang** [comment]
Closed with 5d4e0dee56767b354d009efb86c12c76ca0786ec

**Comment by khellang** [comment]
v2.0.2 is now on NuGet 🙌
